# Generated by Django 5.0.6 on 2024-07-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='portfolio_photos',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio_photos',
            field=models.ManyToManyField(blank=True, to='artisans.portfoliophoto'),
        ),
    ]
