# Generated by Django 5.0.6 on 2024-07-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_remove_artisan_portfolio_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='Telephone',
        ),
        migrations.AddField(
            model_name='users',
            name='Telephone',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
