# Generated by Django 5.0.6 on 2024-07-27 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0003_remove_artisan_telephone_users_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='Metier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artisans.metier'),
        ),
    ]
