# Generated by Django 5.0.6 on 2024-07-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0004_alter_artisan_metier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Lieu_habitation',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Competence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Entreprise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
