# Generated by Django 5.0.6 on 2024-07-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0005_remove_userprofile_lieu_habitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Annee_experience',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
