# Generated by Django 5.0.6 on 2024-07-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0006_alter_userprofile_annee_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Annee_experience',
            field=models.IntegerField(blank=True),
        ),
    ]
