# Generated by Django 5.0.6 on 2024-07-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0007_alter_userprofile_annee_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='portfolio_photos',
        ),
        migrations.AddField(
            model_name='portfoliophoto',
            name='user',
            field=models.ManyToManyField(to='artisans.userprofile'),
        ),
    ]
