# Generated by Django 5.0.6 on 2024-07-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0008_remove_userprofile_portfolio_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Annee_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
