# Generated by Django 5.0.6 on 2024-07-30 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0010_tache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='metier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artisans.metier'),
        ),
    ]
