# Generated by Django 5.0.6 on 2024-07-31 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0011_alter_tache_metier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliophoto',
            name='user',
        ),
        migrations.AddField(
            model_name='portfoliophoto',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artisans.artisan'),
        ),
    ]
