# Generated by Django 5.0.6 on 2024-07-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0012_remove_portfoliophoto_user_portfoliophoto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliophoto',
            name='DateAjout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
