# Generated by Django 5.0.6 on 2024-08-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0014_remove_userprofile_competence_userprofile_competence'),
    ]

    operations = [
        migrations.AddField(
            model_name='metier',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
