# Generated by Django 5.0.6 on 2024-08-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0015_metier_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Lieu_habitation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Telephone',
        ),
        migrations.AddField(
            model_name='client',
            name='Commune',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Ville',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
