# Generated by Django 5.0.6 on 2024-08-03 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0016_remove_client_lieu_habitation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratClientArtisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artisans.artisan')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artisans.client')),
                ('metier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artisans.metier')),
                ('tache', models.ManyToManyField(blank=True, to='artisans.tache')),
            ],
        ),
    ]
