# Generated by Django 5.0.6 on 2024-08-18 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0017_contratclientartisan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratclientartisan',
            name='artisan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artisans.userprofile'),
        ),
    ]
