# Generated by Django 5.0.6 on 2024-08-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0018_alter_contratclientartisan_artisan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
